# Generated by Django 5.0.6 on 2024-07-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(choices=[('package1', 'Package1')], on_delete=django.db.models.deletion.CASCADE, to='bookings.package'),
        ),
    ]
